# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0002_auto_20170307_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='karma_rules',
            field=models.TextField(default='No special rules', max_length=400),
        ),
    ]
