# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0003_project_karma_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karmapoints',
            name='points',
            field=models.IntegerField(),
        ),
    ]
