# Generated by Django 3.0.3 on 2020-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0005_auto_20180326_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'project')},
        ),
    ]
