# Generated by Django 3.0.3 on 2020-03-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0006_auto_20200205_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='karma.Project'),
        ),
    ]
